spring:
  profiles:
#   激活 application-local.yml
    active: local
  application:
    name: nitro-ai-coder-backend
#    mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nitro_ai_coder
    username: root
    password: 123456

# 添加ai 配置
langchain4j:
  open-ai:
    chat-model:
#      最大响应长度
      max-tokens: 8192
#      json output
      strict-json-schema: true
      response-format: json_object

server:
  port: 8123
  servlet:
    context-path: /api



# springdoc-openapi
springdoc:
  group-configs:
    -group: 'default'
#    指定扫描 Controller 包的路径
    package-to-scan: org.example.nitroaicoder.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn