spring:
  application:
    name: nitro-ai-coder-backend
#    mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nitro_ai_coder
    username: root
    password: 123456

server:
  port: 8123
  servlet:
    context-path: /api



# springdoc-openapi
springdoc:
  group-configs:
    -group: 'default'
#    指定扫描 Controller 包的路径
    package-to-scan: org.example.nitroaicoder.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn